### ISSUE TITLE
the output of  _expand_binary_labels

### ISSUE THREAD

**Issue by twmht** [libuyu/GHM_Detection#32]
Hi,

to the best of my knowledge, `_expand_binary_labels`  (https://github.com/libuyu/mmdetection/blob/master/mmdet/models/losses/ghm_loss.py#L8) will output one-hot embedding of the target

i don't understand why you minus 1 from the target (https://github.com/libuyu/mmdetection/blob/master/mmdet/models/losses/ghm_loss.py#L12)

can you elaborate?

thank you

**Comment by libuyu** [comment]
This function is used when the label does not have the one-hot format. So the input label here is the category_id (e.g., 1-80 in COCO).

**Comment by twmht** [comment]
@libuyu 

so why you minus 1 from the target? (because coco index is starting from 1?)

i mean why you do this 

```
bin_labels[inds, labels[inds] - 1] = 1
```

instead of 

```
bin_labels[inds, labels[inds] ] = 1
```

by the way, the input of the pred is [batch, num_class], does num_class contain backgound class?

**Comment by libuyu** [comment]
1. Just because the index of python starts from 0 but the official label starts from 1.

2. For binary labels, num_class does not need to contain the background class. That's because when the label for all the categories becomes 0, it is a background sample.

What's more, I suggest you run the code in debug mode step by step during training, and watch the values of the variables you are interested in. Most problems will have their answers consequently :)

**Comment by twmht** [comment]
ok.

i did not run the code since i don't want to use mmdetection and just want to migrate the loss to my project. so understanding the code is my first step.

thank you
